### PR TITLE
Support different Readingmodes

### PR DESCRIPTION
**Pull request by NicoHood**
@mizuyoukanao check this out. I've corrected the files accordingly. Can you please test this PR? What reading mode does pokemon XD use, so I can document that this mode is 100% tested? Did you also test the other modes?

Superceeds #25 #31 and #34

### CODE REVIEW

**Comment by NicoHood** [comment]
@DinsFire64  @trevor403 can you guys please also test this?

**Comment by mizuyoukanao** [comment]
I've been testing Pokemon XD (mode0).
I can press all buttons and sticks and it seems to be stable.
(There was one bug where setting yAxis/cyAxis to 0 caused the same behavior as 255 in the game, but this is just a Pokemon XD specific bug and should work fine with other software that uses mode0).

**Comment by NicoHood** [comment]
Do you know other software that uses mode 0 (or 1, 2, 4, 5, 6)? Maybe we need to fix this 0->255 "Bug"?

**Comment by mizuyoukanao** [comment]
Sorry, I don't know of any software that uses anything other than mode0 and 3, and I don't have any...
The bug with 0 being 255 only happens in Pokemon XD and can be worked around by setting 1 instead of 0. Other software does not have this problem, so a fix for this is probably not necessary.

**Comment by NicoHood** [comment]
What do you mean by "other software"? Which game?

**Comment by NicoHood** [comment]
I just merged this PR as I do not expect it to cause much additional trouble. It increases the sketch size by ~150 bytes, due to the additional convert method.

**Pull request merged**
